image: node:8.11.4

# Cache modules between builds
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

build:
  stage: build
  script:
   - npm install

test:
  stage: test
  script:
   - npm run test

coverage:
  stage: coverage
  script:
   - npm run test-coverage