image: node:10.13.0

# Cache modules between builds
cache:
  paths:
  - node_modules/

build:
  stage: build
  script:
   - npm rebuild
   - npm install

test:
  stage: test
  script:
   - npm run test

coverage:
  stage: test
  script:
   - npm run test-coverage
  artifacts:
    paths:
      - coverage/

pages:
  stage: deploy
  dependencies:
    - coverage
  script:
    - mv src/credentials.js.example src/credentials.js # Credentials are required
    - CI=false npm run build # Set CI=false or else build fails when there are warnings
    - rm -rf public
    - mkdir public
##  - mv build/* public
    - mv coverage public
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - dev

##code_quality:
##  image: docker:stable
##  variables:
##    DOCKER_DRIVER: overlay2
##  allow_failure: true
##  services:
##    - docker:stable-dind
##  script:
##    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
##    - docker run
##        --env SOURCE_CODE="$PWD"
##        --volume "$PWD":/code
##        --volume /var/run/docker.sock:/var/run/docker.sock
##        "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
##  artifacts:
##    paths: [gl-code-quality-report.json]
