image: node:10.13.0

# Cache modules between builds
cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm ci

test:
  stage: test
  dependencies:
    - build
  script:
    - cp src/credentials.js.example src/credentials.js # Credentials are required
    - npm run test-no-watch

coverage:
  stage: test
  dependencies:
    - build
  script:
    - cp src/credentials.js.example src/credentials.js # Credentials are required
    - npm install -g codecov
    - npm run test-coverage
    - codecov
  artifacts:
    paths:
      - coverage/

pages:
  stage: deploy
  dependencies:
    - coverage
  script:
    - cp src/credentials.js.example src/credentials.js # Credentials are required
    - CI=false npm run build # Set CI=false or else build fails when there are warnings
    - rm -rf public
    - mkdir public
    ##  - mv build/* public
    - mv coverage/lcov-report/ public/coverage
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - dev
