export const TIMER_START = 'TIMER_START';
export const TIMER_PAUSE = 'TIMER_PAUSE';
export const TIMER_RESUME = 'TIMER_RESUME';
export const TIMER_RESET = 'TIMER_RESET';
export const TIMER_STOP = 'TIMER_STOP';

export const EDITOR_STATE_UPDATED = 'EDITOR_STATE_UPDATED';
export const FETCH_TEXTS_START = 'FETCH_TEXTS_START';
export const FETCH_TEXTS_SUCCEEDED = 'FETCH_TEXTS_SUCCEEDED';
export const FETCH_TEXTS_FAILED = 'FETCH_TEXTS_FAILED';
export const GET_TEXT_START = 'GET_TEXT_START';
export const GET_TEXT_SUCCEEDED = 'GET_TEXT_SUCCEEDED';
export const GET_TEXT_FAILED = 'GET_TEXT_FAILED';
export const TEXT_SAVE_REQUESTED = 'TEXT_SAVE_REQUESTED';
export const TEXT_SAVE_SUCCEEDED = 'TEXT_SAVE_SUCCEEDED';
export const TEXT_SAVE_FAILED = 'TEXT_SAVE_SUCCEEDED';

export const TEXT_OPTIONS_UPDATED = 'TEXT_OPTIONS_UPDATED';
export const EXERCISE_OPTIONS_UPDATED = 'EXERCISE_OPTIONS_UPDATED';
export const SPEED_OPTIONS_UPDATED = 'SPEED_OPTIONS_UPDATED';

export const PREPARE_EXERCISE = 'PREPARE_EXERCISE';
export const EXERCISE_SELECTED = 'EXERCISE_SELECTED';
export const EXERCISE_FINISHED = 'EXERCISE_FINISHED';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCEEDED = 'AUTH_SUCCEEDED';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SEND_FEEDBACK_START = 'SEND_FEEDBACK_START';
export const SEND_FEEDBACK_SUCCEEDED = 'SEND_FEEDBACK_SUCCEEDED';
export const SEND_FEEDBACK_FAILED = 'SEND_FEEDBACK_FAILED';
