export const TIMER_START = 'TIMER_START';
export const TIMER_PAUSE = 'TIMER_PAUSE';
export const TIMER_RESUME = 'TIMER_RESUME';
export const TIMER_RESET = 'TIMER_RESET';
export const TIMER_STOP = 'TIMER_STOP';

export const EDITOR_STATE_UPDATED = 'EDITOR_STATE_UPDATED';
export const TEXT_SAVE_REQUESTED = 'TEXT_SAVE_REQUESTED';
export const TEXT_SAVE_SUCCEEDED = 'TEXT_SAVE_SUCCEEDED';
export const TEXT_SAVE_FAILED = 'TEXT_SAVE_SUCCEEDED';

export const TEXT_OPTIONS_UPDATED = 'TEXT_OPTIONS_UPDATED';
export const EXERCISE_OPTIONS_UPDATED = 'EXERCISE_OPTIONS_UPDATED';
export const EXERCISE_SELECTED = 'EXERCISE_SELECTED';
export const EXERCISE_FINISHED = 'EXERCISE_FINISHED';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCEEDED = 'AUTH_SUCCEEDED';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
