export const TIMER_INIT = 'TIMER_INIT';
export const TIMER_START = 'TIMER_START';
export const TIMER_PAUSE = 'TIMER_PAUSE';
export const TIMER_RESUME = 'TIMER_RESUME';
export const TIMER_RESET = 'TIMER_RESET';
export const TIMER_STOP = 'TIMER_STOP';

export const FETCH_TEXT_COLLECTIONS_START = 'FETCH_TEXT_COLLECTIONS_START';
export const FETCH_TEXT_COLLECTIONS_SUCCEEDED = 'FETCH_TEXT_COLLECTIONS_SUCCEEDED';
export const FETCH_TEXT_COLLECTIONS_FAILED = 'FETCH_TEXT_COLLECTIONS_FAILED';
export const FETCH_TEXTS_START = 'FETCH_TEXTS_START';
export const FETCH_TEXTS_SUCCEEDED = 'FETCH_TEXTS_SUCCEEDED';
export const FETCH_TEXTS_FAILED = 'FETCH_TEXTS_FAILED';
export const GET_TEXT_START = 'GET_TEXT_START';
export const GET_TEXT_SUCCEEDED = 'GET_TEXT_SUCCEEDED';
export const GET_TEXT_FAILED = 'GET_TEXT_FAILED';
export const TEXT_SAVE_START = 'TEXT_SAVE_START';
export const TEXT_SAVE_SUCCEEDED = 'TEXT_SAVE_SUCCEEDED';
export const TEXT_SAVE_FAILED = 'TEXT_SAVE_SUCCEEDED';
export const UNSELECT_TEXT = 'UNSELECT_TEXT';

export const TEXT_OPTIONS_UPDATED = 'TEXT_OPTIONS_UPDATED';
export const EXERCISE_OPTIONS_UPDATED = 'EXERCISE_OPTIONS_UPDATED';
export const SPEED_OPTIONS_UPDATED = 'SPEED_OPTIONS_UPDATED';

export const EXERCISE_SELECT = 'EXERCISE_SELECT';
export const EXERCISE_PREPARE = 'EXERCISE_PREPARE';
export const EXERCISE_START = 'EXERCISE_START';
export const EXERCISE_FINISH = 'EXERCISE_FINISH';

export const TEST_PREPARE = 'TEST_PREPARE';
export const TEST_START = 'TEST_START';
export const TEST_FINISH = 'TEST_FINISH';

export const FETCH_QUESTIONS_START = 'FETCH_QUESTIONS_START';
export const FETCH_QUESTIONS_SUCCEEDED = 'FETCH_QUESTIONS_SUCCEEDED';
export const FETCH_QUESTIONS_FAILED = 'FETCH_QUESTIONS_FAILED';
export const ADD_QUESTION_START = 'ADD_QUESTION_START';
export const ADD_QUESTION_SUCCEEDED = 'ADD_QUESTION_SUCCEEDED';
export const ADD_QUESTION_FAILED = 'ADD_QUESTION_FAILED';
export const CHANGE_QUESTION_START = 'CHANGE_QUESTION_START';
export const CHANGE_QUESTION_SUCCEEDED = 'CHANGE_QUESTION_SUCCEEDED';
export const CHANGE_QUESTION_FAILED = 'CHANGE_QUESTION_FAILED';
export const REMOVE_QUESTION_START = 'REMOVE_QUESTION_START';
export const REMOVE_QUESTION_SUCCEEDED = 'REMOVE_QUESTION_SUCCEEDED';
export const REMOVE_QUESTION_FAILED = 'REMOVE_QUESTION_FAILED';
export const ADD_ANSWER_START = 'ADD_ANSWER_START';
export const ADD_ANSWER_SUCCEEDED = 'ADD_ANSWER_SUCCEEDED';
export const ADD_ANSWER_FAILED = 'ADD_ANSWER_FAILED';
export const CHANGE_ANSWER_START = 'CHANGE_ANSWER_START';
export const CHANGE_ANSWER_SUCCEEDED = 'CHANGE_ANSWER_SUCCEEDED';
export const CHANGE_ANSWER_FAILED = 'CHANGE_ANSWER_FAILED';
export const REMOVE_ANSWER_START = 'REMOVE_ANSWER_START';
export const REMOVE_ANSWER_SUCCEEDED = 'REMOVE_ANSWER_SUCCEEDED';
export const REMOVE_ANSWER_FAILED = 'REMOVE_ANSWER_FAILED';

export const FETCH_USERS_START = 'FETCH_USERS_START';
export const FETCH_USERS_SUCCEEDED = 'FETCH_USERS_SUCCEEDED';
export const FETCH_USERS_FAILED = 'FETCH_USERS_FAILED';
export const ADD_USER_START = 'ADD_USER_START';
export const ADD_USER_SUCCEEDED = 'ADD_USER_SUCCEEDED';
export const ADD_USER_FAILED = 'ADD_USER_FAILED';
export const CHANGE_USER_START = 'CHANGE_USER_START';
export const CHANGE_USER_SUCCEEDED = 'CHANGE_USER_SUCCEEDED';
export const CHANGE_USER_FAILED = 'CHANGE_USER_FAILED';
export const FETCH_GROUPS_START = 'FETCH_GROUPS_START';
export const FETCH_GROUPS_SUCCEEDED = 'FETCH_GROUPS_SUCCEEDED';
export const FETCH_GROUPS_FAILED = 'FETCH_GROUPS_FAILED';
export const ADD_GROUP_START = 'ADD_GROUP_START';
export const ADD_GROUP_SUCCEEDED = 'ADD_GROUP_SUCCEEDED';
export const ADD_GROUP_FAILED = 'ADD_GROUP_FAILED';
export const CHANGE_GROUP_START = 'CHANGE_GROUP_START';
export const CHANGE_GROUP_SUCCEEDED = 'CHANGE_GROUP_SUCCEEDED';
export const CHANGE_GROUP_FAILED = 'CHANGE_GROUP_FAILED';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCEEDED = 'AUTH_SUCCEEDED';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SEND_FEEDBACK_START = 'SEND_FEEDBACK_START';
export const SEND_FEEDBACK_SUCCEEDED = 'SEND_FEEDBACK_SUCCEEDED';
export const SEND_FEEDBACK_FAILED = 'SEND_FEEDBACK_FAILED';
